### ISSUE TITLE
Add cucumber e2e tests

### ISSUE THREAD

**Issue by sashokbg** [cytoscape/cytoscape.js-compound-drag-and-drop#21]
Hello,

I am proposing a draft PR to demonstrate how cucumber / gherkin / puppeteer style tests can be implemented for the project.

The tests can be later used to generate a detailed HTML report of what features are in the project and what is their current working state - also known as _living documentation_

https://github.com/sashokbg/cytoscape.js-compound-drag-and-drop/pull/1

PS. The pull request is currently a draft and is pointing towards my fork of the repository.

**Comment by maxkfranz** [comment]
Sounds interesting.  Could you link to an example output page?

**Comment by sashokbg** [comment]
@maxkfranz 

Some screenshots:

![image](https://user-images.githubusercontent.com/10643824/142783104-698dced5-9912-4d17-a5e3-f8add4f313c9.png)

**With attached image, taken by puppeteer during test execution:**

![image](https://user-images.githubusercontent.com/10643824/142783145-34e3d49a-099d-4efa-9f6d-c1c930450b6d.png)

**Comment by sashokbg** [comment]
Closing this suggestion since E2E tests are present in #22
